const actionTypes = {
    GET_HOME: 'GET_HOME',
    CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
    SCROLL_TOP: 'SCROLL_TOP',
    GET_CHART_HOME: 'GET_CHART_HOME',
    SET_TIMER: 'SET_TIMER',
    SET_OPEN_COUNTDOWN: 'SET_OPEN_COUNTDOWN',
    TIMER_DEC: 'TIMER_DEC',
    TIMER_INC: 'TIMER_INC',

    PLAY: 'PLAY',
    SET_CURR_SONG: 'SET_CURR_SONG',
    SET_CURR_SONG_DATA: 'SET_CURR_SONG_DATA',
    IS_ALBUM: 'IS_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SET_AUDIO: 'SET_AUDIO',
    IS_LOADING_DATA: 'IS_LOADING_DATA',
    IS_LOADING_SONG: 'IS_LOADING_SONG',
    SET_RECENT_SONGS: 'RECENT_SONGS',
    SET_RECENT_ALBUMS: 'RECENT_ALBUMS',
    DELETE_RECENT_PLAYLIST: 'DELETE_RECENT_PLAYLIST',
    SEARCH_DATA: 'SEARCH_DATA',
    SEARCH_DATA_ARTIST: 'SEARCH_DATA_ARTIST',
    SEARCH_HISTORY: 'SEARCH_HISTORY',
};

export default actionTypes;
