const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CURR_SONG: 'SET_CURR_SONG',

    PLAY: 'PLAY',
    IS_ALBUM: 'IS_ALBUM',
    PLAYLIST: 'PLAYLIST',
    CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
    SET_AUDIO: 'SET_AUDIO',
    IS_LOADING_DATA: 'IS_LOADING_DATA',
    IS_LOADING_SONG: 'IS_LOADING_SONG',
};

export default actionTypes;
